[2024-09-16T21:00:50.859+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:00:50.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:00:50.864+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:00:50.863+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:00:54.705+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:00:54.703+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:00:54.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:00:54.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 3.919 seconds
[2024-09-16T21:01:23.996+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:01:23.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:01:24.007+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:01:24.006+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:01:24.461+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:01:24.459+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:01:24.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:01:24.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.499 seconds
[2024-09-16T21:01:54.611+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:01:54.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:01:54.613+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:01:54.612+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:01:55.113+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:01:55.111+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:01:55.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:01:55.130+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.526 seconds
[2024-09-16T21:02:25.218+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:02:25.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:02:25.220+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:02:25.220+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:02:25.695+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:02:25.693+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:02:25.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:02:25.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.507 seconds
[2024-09-16T21:02:55.842+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:02:55.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:02:55.845+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:02:55.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:02:56.403+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:02:56.401+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:02:56.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:02:56.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.586 seconds
[2024-09-16T21:03:26.532+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:03:26.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:03:26.535+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:03:26.534+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:03:26.881+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:03:26.879+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:03:26.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:03:26.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.375 seconds
[2024-09-16T21:03:57.011+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:03:57.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:03:57.013+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:03:57.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:03:57.342+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:03:57.340+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:03:57.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:03:57.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.357 seconds
[2024-09-16T21:04:27.485+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:04:27.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:04:27.488+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:04:27.488+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:04:28.126+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:04:28.124+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:04:28.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:04:28.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.671 seconds
[2024-09-16T21:04:58.291+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:04:58.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:04:58.294+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:04:58.294+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:04:59.385+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:04:59.382+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:04:59.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:04:59.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 1.125 seconds
[2024-09-16T21:05:29.541+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:05:29.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:05:29.543+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:05:29.543+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:05:29.983+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:05:29.981+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:05:29.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:05:30.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.466 seconds
[2024-09-16T21:06:00.117+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:06:00.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:06:00.119+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:06:00.119+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:06:00.587+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:06:00.584+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:06:00.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:06:00.629+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.517 seconds
[2024-09-16T21:06:30.757+0000] {processor.py:161} INFO - Started process (PID=128) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:06:30.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:06:30.759+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:06:30.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:06:31.169+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:06:31.167+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:06:31.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:06:31.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.438 seconds
[2024-09-16T21:07:01.303+0000] {processor.py:161} INFO - Started process (PID=137) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:07:01.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:07:01.305+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:07:01.305+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:07:01.772+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:07:01.770+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:07:01.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:07:01.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.511 seconds
[2024-09-16T21:07:31.935+0000] {processor.py:161} INFO - Started process (PID=146) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:07:31.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:07:31.938+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:07:31.938+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:07:32.392+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:07:32.390+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:07:32.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:07:32.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.481 seconds
[2024-09-16T21:08:02.519+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:08:02.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:08:02.522+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:08:02.521+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:08:02.977+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:08:02.975+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:08:02.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:08:03.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.497 seconds
[2024-09-16T21:08:33.133+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:08:33.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:08:33.135+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:08:33.135+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:08:33.582+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:08:33.581+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:08:33.583+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:08:33.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.473 seconds
[2024-09-16T21:09:03.707+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:09:03.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:09:03.710+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:09:03.709+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:09:04.170+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:09:04.168+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:09:04.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:09:04.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.489 seconds
[2024-09-16T21:09:34.329+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:09:34.330+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:09:34.332+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:09:34.331+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:09:34.695+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:09:34.692+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:09:34.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:09:34.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.397 seconds
[2024-09-16T21:10:04.833+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:10:04.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:10:04.835+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:10:04.835+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:10:05.168+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:10:05.166+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:10:05.169+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:10:05.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.362 seconds
[2024-09-16T21:10:35.311+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:10:35.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:10:35.314+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:10:35.313+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:10:35.770+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:10:35.768+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:10:35.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:10:35.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.489 seconds
[2024-09-16T21:11:05.922+0000] {processor.py:161} INFO - Started process (PID=203) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:11:05.924+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:11:05.927+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:11:05.927+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:11:07.146+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:11:07.136+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:11:07.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:11:07.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 1.303 seconds
[2024-09-16T21:11:37.349+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:11:37.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:11:37.351+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:11:37.350+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:11:37.972+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:11:37.970+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:11:37.973+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:11:37.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.654 seconds
[2024-09-16T21:12:08.118+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:12:08.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:12:08.120+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:12:08.120+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:12:08.616+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:12:08.615+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:12:08.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:12:08.641+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.528 seconds
[2024-09-16T21:12:38.763+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:12:38.764+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:12:38.765+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:12:38.765+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:12:39.219+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:12:39.218+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:12:39.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:12:39.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.486 seconds
[2024-09-16T21:13:09.332+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:13:09.333+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:13:09.334+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:13:09.334+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:13:09.674+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:13:09.672+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:13:09.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:13:09.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.370 seconds
[2024-09-16T21:13:39.820+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:13:39.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:13:39.822+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:13:39.822+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:13:40.343+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:13:40.342+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:13:40.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:13:40.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.548 seconds
[2024-09-16T21:14:10.487+0000] {processor.py:161} INFO - Started process (PID=252) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:14:10.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:14:10.489+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:14:10.488+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:14:10.978+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:14:10.977+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:14:10.979+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:14:11.000+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.520 seconds
[2024-09-16T21:14:41.105+0000] {processor.py:161} INFO - Started process (PID=260) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:14:41.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:14:41.107+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:14:41.107+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:14:41.576+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:14:41.574+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:14:41.577+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:14:41.601+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.500 seconds
[2024-09-16T21:15:11.732+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:15:11.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:15:11.734+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:15:11.734+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:15:12.257+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:15:12.256+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:15:12.258+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:15:12.277+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.550 seconds
[2024-09-16T21:15:42.323+0000] {processor.py:161} INFO - Started process (PID=276) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:15:42.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:15:42.325+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:15:42.325+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:15:42.891+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:15:42.890+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:15:42.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:15:42.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.593 seconds
[2024-09-16T21:16:13.031+0000] {processor.py:161} INFO - Started process (PID=284) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:16:13.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:16:13.034+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:16:13.034+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:16:13.395+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:16:13.393+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:16:13.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:16:13.420+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.395 seconds
[2024-09-16T21:16:43.548+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:16:43.549+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:16:43.553+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:16:43.552+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:16:44.683+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:16:44.680+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:16:44.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:16:44.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 1.190 seconds
