[2024-09-16T21:00:50.859+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:00:50.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:00:50.864+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:00:50.863+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:00:54.705+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:00:54.703+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:00:54.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:00:54.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 3.919 seconds
[2024-09-16T21:01:23.996+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:01:23.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:01:24.007+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:01:24.006+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:01:24.461+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:01:24.459+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:01:24.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:01:24.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.499 seconds
[2024-09-16T21:01:54.611+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:01:54.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:01:54.613+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:01:54.612+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:01:55.113+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:01:55.111+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:01:55.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:01:55.130+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.526 seconds
[2024-09-16T21:02:25.218+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:02:25.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:02:25.220+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:02:25.220+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:02:25.695+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:02:25.693+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:02:25.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:02:25.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.507 seconds
[2024-09-16T21:02:55.842+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:02:55.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:02:55.845+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:02:55.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:02:56.403+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:02:56.401+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:02:56.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:02:56.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.586 seconds
[2024-09-16T21:03:26.532+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:03:26.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:03:26.535+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:03:26.534+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:03:26.881+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:03:26.879+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:03:26.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:03:26.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.375 seconds
[2024-09-16T21:03:57.011+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:03:57.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:03:57.013+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:03:57.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:03:57.342+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:03:57.340+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:03:57.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:03:57.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.357 seconds
[2024-09-16T21:04:27.485+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:04:27.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:04:27.488+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:04:27.488+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:04:28.126+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:04:28.124+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:04:28.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:04:28.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.671 seconds
[2024-09-16T21:04:58.291+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:04:58.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:04:58.294+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:04:58.294+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:04:59.385+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:04:59.382+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:04:59.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:04:59.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 1.125 seconds
[2024-09-16T21:05:29.541+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/dag.py
[2024-09-16T21:05:29.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-09-16T21:05:29.543+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:05:29.543+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-09-16T21:05:29.983+0000] {logging_mixin.py:188} INFO - [2024-09-16T21:05:29.981+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    with DAG(
         ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 519, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-16T21:05:29.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-09-16T21:05:30.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.466 seconds
